version: '2'

services:
    db:
        image: mysql:5.7
        volumes:
          - /opt/db_data:/var/lib/mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: 1234567899
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
 

    php:
        image: nguyenan122/php-editor:ver2
        volumes:
            - ./html:/var/www/html
        volumes:
            - ./html:/var/www/html
            - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        links:
            - db
    web1:
        depends_on:
            - db
            - php
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./html:/var/www/html
            - ./nginx/tuan.conf:/etc/nginx/conf.d/default.conf
        links:
            - php:php
            - db






